version: '3'

services:
  db_mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./database/data:/var/lib/mysql
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: vocacional
      MYSQL_ROOT_PASSWORD: vocacional
      MYSQL_DATABASE: vocacional
